name: lim-deriv/python-deriv-api/update_schema_flow
on:
  schedule:
  - cron: 0 0 * * *
#   # 'filters' was not transformed because there is no suitable equivalent in GitHub Actions
jobs:
  update_schema:
    runs-on: ubuntu-latest
    container:
      image: python:${{ env.python-version }}
      env:
        PIPENV_VENV_IN_PROJECT: true
    env:
      python-version: 3.9.6
    steps:
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - uses: actions/checkout@v4.0.0
    - name: config git
      run: |-
        git config --global user.email "nobody@deriv.com"
        git config --global user.name "Nobody"
    - name: update schema
      run: |-
        git clone https://github.com/binary-com/deriv-developers-portal.git /tmp/deriv-developers-portal
        curl -L https://cpanmin.us | perl - --sudo App::cpanminus
        sudo cpanm -n Dir::Self File::Basename JSON::MaybeXS Log::Any Path::Tiny Template Syntax::Keyword::Try
        BINARYCOM_API_SCHEMA_PATH=/tmp/deriv-developers-portal/config/v3 perl scripts/regen-py.pl
        if [[ $(git diff --shortstat) == ' 2 files changed, 2 insertions(+), 2 deletions(-)' ]]
        then
          echo 'Schema no change'
          exit 0
        fi
        echo "Schama updated"
        pip3 install bump
        NEXT_VER=$(bump)
        sed -i '/# Changelog/{s/$/\n\n## NEXTVER\n\nSync API/}' CHANGELOG.md
        sed -i "s/NEXTVER/$NEXT_VER/g" CHANGELOG.md
        git add .
        git commit -m 'update schema automatically'
        git push origin HEAD:master
