# This file was automatically generated by scripts/regen-py.pl at 20220627-142751

# streams_list is the list of subscriptions msg_types available.
# Please update it by scripts/regen-py.pl
# Refer https://developers.binary.com/
streams_list = [ 'balance',  'buy',  'cashier_payments',  'exchange_rates',  'p2p_advert_info',  'p2p_advertiser_create',  'p2p_advertiser_info',  'p2p_order_create',  'p2p_order_info',  'p2p_order_list',  'proposal',  'proposal_open_contract',  'ticks',  'ticks_history',  'transaction',  'website_status', ]
